---
title: "Data Dictionary"
author: "Joohyun Kim"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


| Field Name | Data Type | Description                                                    | Example             |
|:------------:|:-----------:|:----------------------------------------------------------------|:---------------------|
| Date_UTC   | character | Date (Universal Time Correlated)                               | 2000-01-01T00:00:00 |
| dbn_nez    | float     | Magnetic field north component, NEZ coordinates [nT]           | -51.6               |
| dbe_nez    | float     | Magnetic field east component, NEZ coordinates [nT]            | -5.7                |
| dbz_nez    | float     | Magnetic field vertical component, NEZ coordinates [nT]        | 15.0                |
| dbn_geo    | float     | Magnetic field north component, geographic coordinates [nT]    | -51.8               |
| dbe_geo    | float     | Magnetic field east component, geographic coordinates [nT]     | 3.5                 |
| dbz_geo    | float     | Magnetic field vertical component, geographic coordinates [nT] | 15.0                |
| Extent     | double    | Extent of Record [seconds]                                     | 60                  |
| IAGA       | character | Station Identifier                                             | FRD                 |
| GEOLON     | float     | Geographic Longitude [degrees]                                 | 282.63              |
| GEOLAT     | float     | Geographic Latitude [degrees]                                  | 38.2                |
| MAGON      | float     | AACGM Longitude [degrees]                                      | -2.13               |
| MAGLAT     | float     | AACGM Latitude [degrees]                                       | 49.08               |
| MLT        | float     | AACGM Magnetic Local Time [h]                                  | 18.70               |
| MCOLAT     | float     | AACGM Colatitude [degrees]                                     | 40.92               |
| IGRF_DECL  | float     | Magnetic Declination [degrees]                                 | -10.18              |
| SZA        | float     | Solar Zenith Angle [degrees]                                   | 113.02              |

- AACGM: Altitude adjusted corrected geomagnetic
- nT: nano tesla (a unit of magnetic flux)

